# Generated by Django 4.0.4 on 2022-05-10 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('2e6e2818-e146-4ea1-8e43-2e83907f5643'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('age', models.IntegerField()),
                ('specialty', models.CharField(default='Medicina general', max_length=255)),
                ('entrance_time', models.TimeField()),
                ('exit_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b8050cf8-3675-4e72-8cd8-9c4e4e36d51e'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('age', models.IntegerField()),
                ('medical_history', models.CharField(max_length=500)),
                ('patient_relantionship', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b6b73aad-dea9-400b-ae92-51f2c97308a9'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('age', models.IntegerField()),
                ('medical_history', models.CharField(max_length=500)),
            ],
        ),
    ]
