# Generated by Django 4.0.4 on 2022-05-10 17:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0002_alter_doctor_id_alter_doctor_specialty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.UUIDField(default=uuid.UUID('50417b90-0217-4b34-9bda-dabc5066b1ca'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parent',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5f2fd7cf-b091-4db5-95f7-c21ba1da622c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('03148a71-d6c4-4b04-866e-04a618e4d5b4'), primary_key=True, serialize=False),
        ),
    ]
