# Generated by Django 4.0.4 on 2022-05-10 17:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0003_alter_doctor_id_alter_parent_id_alter_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a52286db-6ee9-4785-bc81-dcc53cb4b06b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parent',
            name='id',
            field=models.UUIDField(default=uuid.UUID('adea3258-5bb2-4e0e-9cbe-aa1a0942544f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b81f8d4b-3cca-43cf-9a29-b4c359aaae15'), editable=False, primary_key=True, serialize=False),
        ),
    ]
